version: 0.2
env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Docker requires the privileged flag in the CodeBuild configuration
      - docker info
  build:
    commands:
      - ls -lR
      - git status --verbose
      - yarn --prod --frozen-lockfile
      - yarn prep
      - docker run --rm
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        amazon/aws-cli sts get-caller-identity
      - docker run --rm 
        -v $(pwd):/apps -u $(id -u):$(id -g)
        -w /apps/aws 
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        alpine/terragrunt
        terragrunt plan -out tf.plan
      - docker run --rm
        -v $(pwd):/apps -u $(id -u):$(id -g)
        -w /apps/aws 
        indeni/cloudrail-cli
        run -p tf.plan -d . --auto-approve -v --api-key $CLOUDRAIL_API_KEY
      - docker run --rm 
        -v $(pwd):/apps -u $(id -u):$(id -g)
        -w /apps/aws 
        -e AWS_DEFAULT_REGION -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
        alpine/terragrunt
        terragrunt apply -auto-approve tf.plan

